#!/bin/bash

export _JAVA_AWT_WM_NONREPARENTING=1 
copyq &

# fedora
#/usr/libexec/polkit-gnome-authentication-agent-1 &

# arch
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
conky -c ~/.config/conky/gruvbox-material.conkyrc &
./.fehbg &
# /usr/bin/emacs --daemon &
nm-applet &

dwm
